# Site settings
title: Portugal
client:
  name: Ein Ort, der Sehnsucht weckt
  link: "https://www.visitportugal.com/de"
core-se-link: https://www.secretescapes.de/aktuelle-angebote?utm_source=SE&utm_medium=hub&utm_campaign=portugal_DE_2019
se-tracking-link: "?utm_source=SE&utm_medium=hub&utm_campaign=portugal_DE_2019"
description: >
  Portugal hat viele Gesichter: Neben rauen Küstenabschnitten im Süden bis hin zur grünen Dünen­landschaft im Norden. Die Lage am Atlantik hat das Land der Eroberer nicht nur geschichtlich geprägt.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/portugal-herbst-2019" # the subpath of your site, e.g. /blog/
img:     "/de/portugal-herbst-2019/_assets/img"
css:     "/de/portugal-herbst-2019/_assets/css"
js:      "/de/portugal-herbst-2019/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
